### ISSUE TITLE
Is this Chart in use?!

### ISSUE THREAD

**Issue by chokosabe** [redpanda-data/redpanda-connect-helm-chart#105]
Getting this error when running this chart

level=info msg="Running main config from specified file" @service=benthos benthos_version=v4.27.0 path=/benthos.yaml
level=error msg="Config lint error" @service=benthos lint="/streams/benthos.yaml(1,1) field http not recognised"
level=error msg="Shutting down due to stream linter errors, to prevent shutdown run Benthos with --chilled" @service=benthos

which basically is referring to /streams/benthos.yaml. The http section is added by the chart. Do we need to replace it or something.

Almost feels like this chart is designed to not run. Its a bit of a mess

**Comment by charlie-haley** [comment]
Hey @chokosabe, could you send over your `values.yaml` file that you're trying to deploy the chart with?

**Comment by chokosabe** [comment]
values.yaml file looks like this - being deployed using rancher.
I went back and disabled stream in values.yaml and the error changed to:

```
Container: benthos
Filter
Connected
level=info msg="Running main config from specified file" @service=benthos benthos_version=v4.27.0 path=/benthos.yaml
level=info msg="Launching a benthos instance, use CTRL+C to close" @service=benthos
level=info msg="Output type stdout is now active" @service=benthos label=no_config_out path=root.output
level=info msg="Input type generate is now active" @service=benthos label=no_config_in path=root.input
This Benthos instance is unconfigured!
```

```
affinity: {}
args: []
autoscaling:
  enabled: false
  maxReplicas: 12
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 1
command: []
commonLabels: {}
config: {}
deployment:
  annotations: {}
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /ping
      port: http
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 2
  podAnnotations: {}
  podLabels: {}
  readinessProbe:
    failureThreshold: 1
    httpGet:
      path: /ready
      port: http
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 2
  replicaCount: 1
  restartPolicy: Always
  rolloutConfigMap: true
  terminationGracePeriodSeconds: 60
env: []
envFrom: []
extraVolumeMounts: []
extraVolumes: []
fullnameOverride: ''
http:
  address: 0.0.0.0:4195
  cors:
    enabled: false
  debug_endpoints: false
  enabled: false
  root_path: /benthos
image:
  pullPolicy: IfNotPresent
  repository: jeffail/benthos
  tag: latest
imagePullSecrets: []
ingress:
  annotations: {}
  className: ''
  enabled: false
  hosts: []
  tls: []
initContainers: []
nameOverride: ''
nodeSelector: {}
podDisruptionBudget:
  enabled: false
podSecurityContext: {}
resources: {}
securityContext: {}
service:
  extraPorts: null
  name: http
  port: 80
  protocol: TCP
  targetPort: http
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: ''
serviceMonitor:
  enabled: false
  interval: 10s
  scheme: http
streams:
  api:
    enable: true
  enabled: false
  streamsConfigMap: benthos-config
tolerations: []
topologySpreadConstraints: []
updateStrategy: {}
watch: false
global:
  cattle:
    systemProjectId:
```

Followed the setup instructions re ConfigMap.
