### ISSUE TITLE
[bug] Configuration creates a ConfigMap instead of a Secret

### ISSUE THREAD

**Issue by dotdc** [redpanda-data/redpanda-connect-helm-chart#99]
Hello,

The chart currently creates a ConfigMap to store the benthos configuration file. 
This could be an issue because there could be secrets inside.

Example:

```
output:
  broker:
    outputs:
      - elasticsearch:
          basic_auth:
            enabled: true
            username: "${elasticsearch_user}"
            password: "${elasticsearch_pass}"
```

Would like to store the configuration in a Kubernetes Secret rather than in a ConfigMap.

> [!NOTE]
> Will create a PR to solve the issue.
